### ISSUE TITLE
babytux exits when baby presses multimedia buttons

### ISSUE THREAD

**Issue by bjmgeek** [jaredly/babytux#2]
python game.py
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 30
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 30
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 55
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 56
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 59
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 58
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 30
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 30
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 30
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 55
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 56
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 59
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 58
nvfx_screen_get_param:95 -  Warning: unknown PIPE_CAP 30
Traceback (most recent call last):
  File "game.py", line 125, in <module>
    Main().mainLoop()
  File "/home/knoppix/babytux/app.py", line 62, in mainLoop
    self.win.dispatch_events()
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/**init**.py", line 1140, in dispatch_events
    self.dispatch_platform_event(e)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/**init**.py", line 1169, in dispatch_platform_event
    event_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/**init**.py", line 1326, in _event_key
    text, symbol = self._event_text_symbol(ev)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/__init__.py", line 1262, in _event_text_symbol
    symbol = ord(unichr(symbol).lower())
ValueError: unichr() arg not in range(0x110000) (wide Python build)

**Comment by jaredly** [comment]
I *think* this might be fixed by #8, would love to get confirmation.

**Comment by bjmgeek** [comment]
I will try to check.  I don't have the laptop with multimedia keys anymore :-)
